### PR TITLE
Fix CS:GO GetSpew support

### PR DESCRIPTION
**Pull request by peace-maker**
GetSpew is implemented in the current engine, but uses the fastcall calling convention on windows now.

Add gamedata for CS:GO back in as well as a "UseFastcall" key to indicate the calling convention for the GetSpew call.

### CODE REVIEW

**Comment by GoD-Tony** [comment]
Pretty cool that this works now. Just be careful of pushing auto-updated gamedata that might break users running an older version of the extension.

**Comment by peace-maker** [comment]
On the other hand this could be a nice way to get people to update the extension 😉 
You could wait for the next breaking csgo update to push the new gamedata and not put it on the autoupdater yet.

**Comment by asherkin** [comment]
@peace-maker @GoD-Tony could you look over the changes I just pushed?

@peace-maker we can't have old versions start crashing in any case...

**Comment by peace-maker** [comment]
We can go without the "UseFastcall" key now and just check for the "GetSpewFastcall" first before trying "GetSpew", just always using the "GetSpewFastcall" signature if it is valid.

**Comment by asherkin** [comment]
That works for now, but the UseFastcall key allows a more specific gamedata block or user override gamedata to opt for the non-fastcall version.

**Comment by peace-maker** [comment]
More options are good I guess? This looks good.

**Pull request merged**
